# config.py
from binance.client import Client

SYMBOL = "BTCUSDT"
BASE_INTERVAL = Client.KLINE_INTERVAL_1MINUTE
BASE_INTERVAL_STR = "1m"
ANALYSIS_INTERVAL = "1min"
TP=4
SL=-3
LIMIT = 1000
SALDO_INICIAL = 200
APALANCAMIENTO = 15
DIAS_TEST= 60
CSV_FILE = f"data/{SYMBOL}_{BASE_INTERVAL_STR}.csv"
TIMEZONE = "Etc/GMT+4"
